### ISSUE TITLE
Provide a standalone generator

### ISSUE THREAD

**Issue by OLibutzki** [nils-christian/feature-gen#2]
Because of https://github.com/eclipse/xtext-xtend/issues/664 the solution which is provided by feature-gen doesn't work as expected. It would be great to have a workaround.

The proposed solution is to have a standalone generator which picks up an xml file and generates some Java code (like the Xtend Active annotation processor does).

The generator application can be called using the exec-maven-plugin. Eclipse integration (Incremetal build) can be achieved by mapping the plugin execution via m2e.

The code generator itself can implemented in Xtend, but you just do not rely on the annoation processing feature.

**Comment by nils-christian** [comment]
Hi Oliver,

Thank you very much for your proposal. I plan to implement two corresponding generators with 1.1.0.

Best regards

  Nils

**Comment by nils-christian** [comment]
Both generators have been implemented and will be available with 2.0.0.
